-- MySQL Workbench Synchronization
-- Generated: 2018-02-27 16:18
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Rafael Gomides

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `beowl406_arietama-test` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`FORNECEDORES` (
  `COD_FORNECEDOR` INT(11) NOT NULL AUTO_INCREMENT,
  `FOR_NOME_FANTASIA` VARCHAR(200) NULL DEFAULT NULL,
  `FOR_RAZAO_SOCIAL` VARCHAR(200) NOT NULL,
  `FOR_CNPJ` INT(11) NOT NULL,
  `FOR_INSCRICAO_ESTADUAL` INT(11) NULL DEFAULT NULL,
  `FOR_LOGRADOURO` VARCHAR(255) NOT NULL,
  `FOR_NUM-LOGRADOURO` INT(11) NOT NULL,
  `FOR_COMPLEMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_BAIRRO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_CIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_ESTADO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_PAIS` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_TELEFONE` INT(11) NOT NULL,
  `FOR_PABX` INT(11) NULL DEFAULT NULL,
  `FOR_CELULAR` INT(11) NULL DEFAULT NULL,
  `FOR_EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `FOR_CEP` INT(11) NULL DEFAULT NULL,
  `FOR_CONTATO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_OBS` VARCHAR(255) NULL DEFAULT NULL,
  `FOR_DISTANCIA_FISICA` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_REFERENCIAS` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_CUSTO_FRETE` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_QUALIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_CAPACIDADE_FORNECIMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_PRAZO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_FORMA_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_FORMA_PAGAMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `FOR_STATUS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_FORNECEDOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`PRODUTOS` (
  `COD_PRODUTO` INT(11) NOT NULL AUTO_INCREMENT,
  `PRO_DESCRICAO` VARCHAR(255) NOT NULL,
  `PRO_GRUPO` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_NF_ENTRADA` INT(11) NULL DEFAULT NULL,
  `PRO_VALOR_COMPRA` DECIMAL NOT NULL,
  `PRO_PERCENTUAL_GANHO` INT(11) NULL DEFAULT NULL,
  `PRO_VALOR_VENDA_BASE` DECIMAL NOT NULL,
  `PRO_TAMANHO` INT(11) NULL DEFAULT NULL,
  `PRO_DURABILIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_VALIDADE` DATE NULL DEFAULT NULL,
  `PRO_MODELO` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_PESO` DECIMAL NULL DEFAULT NULL,
  `PRO_EMBALAGEM` VARCHAR(100) NULL DEFAULT NULL,
  `PRO_VARIEDADE` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_QUALIDADE` VARCHAR(255) NULL DEFAULT NULL,
  `PRO_REPUTACAO` INT(11) NULL DEFAULT NULL,
  `PRO_POSICIONAMENTO` INT(11) NULL DEFAULT NULL,
  `PRO_MARCA` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_INSTALACAO` VARCHAR(255) NULL DEFAULT NULL,
  `PRO_INFORMACOES` VARCHAR(255) NULL DEFAULT NULL,
  `PRO_MANUTENCAO` VARCHAR(255) NULL DEFAULT NULL,
  `PRO_GARANTIA` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_DEVOLUCAO` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_IMAGEM` VARCHAR(45) NULL DEFAULT NULL,
  `PRO_STATUS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_PRODUTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`COMPRAS` (
  `FORNECEDORES_COD_FORNECEDOR` INT(11) NOT NULL,
  `PRODUTOS_COD_PRODUTO` INT(11) NOT NULL,
  `COD_ORDEM_COMPRA` INT(11) NOT NULL AUTO_INCREMENT,
  `COM_QUANTIDADE` INT(11) NULL DEFAULT NULL,
  `COM_VALOR` DECIMAL NULL DEFAULT NULL,
  `COM_FRETE` DECIMAL NULL DEFAULT NULL,
  `COM_DESCONTO` DECIMAL NULL DEFAULT NULL,
  `COM_PRAZO_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `COM_MODO_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `COM_DATA` DATE NULL DEFAULT NULL,
  `COM_QUALIDADE_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `COM_NOME_ENTREGADOR` VARCHAR(100) NULL DEFAULT NULL,
  `COM_IDENTIFICACAO_ENTREGADOR` VARCHAR(45) NULL DEFAULT NULL,
  `COM_VEICULO` VARCHAR(100) NULL DEFAULT NULL,
  `COM_TIPO_VEICULO` VARCHAR(45) NULL DEFAULT NULL,
  `COM_PLACA_VEICULO` VARCHAR(7) NULL DEFAULT NULL,
  `COM_NF_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `COM_NF_PACOTE` VARCHAR(45) NULL DEFAULT NULL,
  `COM_INFORMACAO_LOTE` VARCHAR(255) NULL DEFAULT NULL,
  `COM_CONCLUSAO` VARCHAR(45) NULL DEFAULT NULL,
  `COM_STATUS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ORDEM_COMPRA`, `FORNECEDORES_COD_FORNECEDOR`, `PRODUTOS_COD_PRODUTO`),
  INDEX `fk_FORNECEDORES_has_PRODUTOS_PRODUTOS1_idx` (`PRODUTOS_COD_PRODUTO` ASC),
  INDEX `fk_FORNECEDORES_has_PRODUTOS_FORNECEDORES_idx` (`FORNECEDORES_COD_FORNECEDOR` ASC),
  CONSTRAINT `fk_FORNECEDORES_has_PRODUTOS_FORNECEDORES`
    FOREIGN KEY (`FORNECEDORES_COD_FORNECEDOR`)
    REFERENCES `beowl406_arietama-test`.`FORNECEDORES` (`COD_FORNECEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FORNECEDORES_has_PRODUTOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_COD_PRODUTO`)
    REFERENCES `beowl406_arietama-test`.`PRODUTOS` (`COD_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ORDEM DE COMPRA';

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`ESTOQUES` (
  `COD_ESTOQUE` INT(11) NOT NULL AUTO_INCREMENT,
  `EST_DESCRICAO` VARCHAR(255) NULL DEFAULT NULL,
  `SETORES_COD_SETOR` INT(11) NOT NULL,
  `EST_STATUS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ESTOQUE`, `SETORES_COD_SETOR`),
  INDEX `fk_ESTOQUES_SETORES1_idx` (`SETORES_COD_SETOR` ASC),
  CONSTRAINT `fk_ESTOQUES_SETORES1`
    FOREIGN KEY (`SETORES_COD_SETOR`)
    REFERENCES `beowl406_arietama-test`.`SETORES` (`COD_SETOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`SETORES` (
  `COD_SETOR` INT(11) NOT NULL AUTO_INCREMENT,
  `SET_DESCRICAO` VARCHAR(45) NULL DEFAULT NULL,
  `SET_TIPO` VARCHAR(45) NULL DEFAULT NULL,
  `SET_TAMANHO` VARCHAR(45) NULL DEFAULT NULL,
  `SET_CAPACIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `SET_MEDIDA` VARCHAR(45) NULL DEFAULT NULL,
  `SET_OBSERVACAO` VARCHAR(255) NULL DEFAULT NULL,
  `SET_CONTROLE_TEMPERATURA` VARCHAR(45) NULL DEFAULT NULL,
  `SET_SEGURANCA` VARCHAR(45) NULL DEFAULT NULL,
  `SET_LOCALIZACAO` VARCHAR(45) NULL DEFAULT NULL,
  `SET_STATUS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_SETOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`ARMAZENAMENTOS` (
  `COMPRAS_COD_ORDEM_COMPRA` INT(11) NOT NULL,
  `COMPRAS_FORNECEDORES_COD_FORNECEDOR` INT(11) NOT NULL,
  `COMPRAS_PRODUTOS_COD_PRODUTO` INT(11) NOT NULL,
  `ESTOQUES_COD_ESTOQUE` INT(11) NOT NULL,
  `ESTOQUES_SETORES_COD_SETOR` INT(11) NOT NULL,
  `COD_ARMAZENAMENTO` INT(11) NOT NULL AUTO_INCREMENT,
  `ARM_QUANTIDADE_ARMAZENADA` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ARMAZENAMENTO`, `COMPRAS_COD_ORDEM_COMPRA`, `COMPRAS_FORNECEDORES_COD_FORNECEDOR`, `COMPRAS_PRODUTOS_COD_PRODUTO`, `ESTOQUES_COD_ESTOQUE`, `ESTOQUES_SETORES_COD_SETOR`),
  INDEX `fk_COMPRAS_has_ESTOQUES_ESTOQUES1_idx` (`ESTOQUES_COD_ESTOQUE` ASC, `ESTOQUES_SETORES_COD_SETOR` ASC),
  INDEX `fk_COMPRAS_has_ESTOQUES_COMPRAS1_idx` (`COMPRAS_COD_ORDEM_COMPRA` ASC, `COMPRAS_FORNECEDORES_COD_FORNECEDOR` ASC, `COMPRAS_PRODUTOS_COD_PRODUTO` ASC),
  CONSTRAINT `fk_COMPRAS_has_ESTOQUES_COMPRAS1`
    FOREIGN KEY (`COMPRAS_COD_ORDEM_COMPRA` , `COMPRAS_FORNECEDORES_COD_FORNECEDOR` , `COMPRAS_PRODUTOS_COD_PRODUTO`)
    REFERENCES `beowl406_arietama-test`.`COMPRAS` (`COD_ORDEM_COMPRA` , `FORNECEDORES_COD_FORNECEDOR` , `PRODUTOS_COD_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRAS_has_ESTOQUES_ESTOQUES1`
    FOREIGN KEY (`ESTOQUES_COD_ESTOQUE` , `ESTOQUES_SETORES_COD_SETOR`)
    REFERENCES `beowl406_arietama-test`.`ESTOQUES` (`COD_ESTOQUE` , `SETORES_COD_SETOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ORDEM DE ARMAZENAMENTO';

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`CLIENTES` (
  `COD_CLIENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `CLI_NOME` VARCHAR(45) NOT NULL,
  `CLI_SOBRENOME` VARCHAR(150) NULL DEFAULT NULL,
  `CLI_TRATAMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `CLI_LOGRADOURO` VARCHAR(100) NULL DEFAULT NULL,
  `CLI_NUM_LOGRADOURO` INT(11) NULL DEFAULT NULL,
  `CLI_BAIRRO` VARCHAR(45) NULL DEFAULT NULL,
  `CLI_CIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `CLI_ESTADO` VARCHAR(45) NULL DEFAULT NULL,
  `CLI_PAIS` VARCHAR(45) NULL DEFAULT NULL,
  `CLI_TELEFONE` INT(11) NULL DEFAULT NULL,
  `CLI_CELULAR` INT(11) NULL DEFAULT NULL,
  `CLI_EMAIL` VARCHAR(100) NULL DEFAULT NULL,
  `CLI_RG` INT(11) NULL DEFAULT NULL,
  `CLI_CPF` INT(11) NULL DEFAULT NULL,
  `CLI_DATA_NASCIMENTO` DATE NULL DEFAULT NULL,
  `CLI_NOME_PAI` VARCHAR(100) NULL DEFAULT NULL,
  `CLI_NOME_MAE` VARCHAR(100) NULL DEFAULT NULL,
  `CLI_OUTROS_DOCS` VARCHAR(255) NULL DEFAULT NULL,
  `CLI_TELEFONE_CONTATO` INT(11) NULL DEFAULT NULL,
  `CLI_TELEFONE_COMERCIAL` INT(11) NULL DEFAULT NULL,
  `CLI_OBSERVACAO` VARCHAR(255) NULL DEFAULT NULL,
  `CLI_STATUS` INT(11) NULL DEFAULT NULL,
  `CLI_CNPJ` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_CLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`VENDAS` (
  `COD_VENDA` INT(11) NOT NULL AUTO_INCREMENT,
  `VEN_DATA` DATE NULL DEFAULT NULL,
  `VEN_HORA` TIME NULL DEFAULT NULL,
  `VEN_TIPO` VARCHAR(45) NULL DEFAULT NULL,
  `VEN_TIPO_PAGAMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `VEN_ENTREGA` INT(11) NULL DEFAULT NULL,
  `VEN_SUB_TOTAL` DECIMAL NULL DEFAULT NULL,
  `VEN_DESCONTO` DECIMAL NULL DEFAULT NULL,
  `VEN_TOTAL` DECIMAL NULL DEFAULT NULL,
  `VEN_TIPO_CLIENTE` INT(11) NULL DEFAULT NULL,
  `VEN_FORMA_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `VEN_NF` INT(11) NULL DEFAULT NULL,
  `VEN_PRESENTE` INT(11) NULL DEFAULT NULL,
  `VEN_TIPO_PRESENTE` VARCHAR(45) NULL DEFAULT NULL,
  `VEN_ENTREGA_AGENDAMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `VEN_TIPO_ENTREGA` VARCHAR(45) NULL DEFAULT NULL,
  `CLIENTES_COD_CLIENTE` INT(11) NOT NULL,
  PRIMARY KEY (`COD_VENDA`, `CLIENTES_COD_CLIENTE`),
  INDEX `fk_VENDAS_CLIENTES1_idx` (`CLIENTES_COD_CLIENTE` ASC),
  CONSTRAINT `fk_VENDAS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_COD_CLIENTE`)
    REFERENCES `beowl406_arietama-test`.`CLIENTES` (`COD_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `beowl406_arietama-test`.`PEDIDOS` (
  `VENDAS_COD_VENDA` INT(11) NOT NULL,
  `VENDAS_CLIENTES_COD_CLIENTE` INT(11) NOT NULL,
  `ARMAZENAMENTOS_COD_ARMAZENAMENTO` INT(11) NOT NULL,
  `ARMAZENAMENTOS_COMPRAS_COD_ORDEM_COMPRA` INT(11) NOT NULL,
  `ARMAZENAMENTOS_COMPRAS_FORNECEDORES_COD_FORNECEDOR` INT(11) NOT NULL,
  `ARMAZENAMENTOS_COMPRAS_PRODUTOS_COD_PRODUTO` INT(11) NOT NULL,
  `ARMAZENAMENTOS_ESTOQUES_COD_ESTOQUE` INT(11) NOT NULL,
  `ARMAZENAMENTOS_ESTOQUES_SETORES_COD_SETOR` INT(11) NOT NULL,
  `COD_PEDIDO` INT(11) NOT NULL AUTO_INCREMENT,
  `PED_QUANTIDADE` DECIMAL NOT NULL,
  `PED_PRECO` DECIMAL NOT NULL,
  `PED_SUB-TOTAL` DECIMAL NOT NULL,
  PRIMARY KEY (`COD_PEDIDO`),
  INDEX `fk_VENDAS_has_ARMAZENAMENTOS_ARMAZENAMENTOS1_idx` (`ARMAZENAMENTOS_COD_ARMAZENAMENTO` ASC, `ARMAZENAMENTOS_COMPRAS_COD_ORDEM_COMPRA` ASC, `ARMAZENAMENTOS_COMPRAS_FORNECEDORES_COD_FORNECEDOR` ASC, `ARMAZENAMENTOS_COMPRAS_PRODUTOS_COD_PRODUTO` ASC, `ARMAZENAMENTOS_ESTOQUES_COD_ESTOQUE` ASC, `ARMAZENAMENTOS_ESTOQUES_SETORES_COD_SETOR` ASC),
  INDEX `fk_VENDAS_has_ARMAZENAMENTOS_VENDAS1_idx` (`VENDAS_COD_VENDA` ASC, `VENDAS_CLIENTES_COD_CLIENTE` ASC),
  CONSTRAINT `fk_VENDAS_has_ARMAZENAMENTOS_VENDAS1`
    FOREIGN KEY (`VENDAS_COD_VENDA` , `VENDAS_CLIENTES_COD_CLIENTE`)
    REFERENCES `beowl406_arietama-test`.`VENDAS` (`COD_VENDA` , `CLIENTES_COD_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDAS_has_ARMAZENAMENTOS_ARMAZENAMENTOS1`
    FOREIGN KEY (`ARMAZENAMENTOS_COD_ARMAZENAMENTO` , `ARMAZENAMENTOS_COMPRAS_COD_ORDEM_COMPRA` , `ARMAZENAMENTOS_COMPRAS_FORNECEDORES_COD_FORNECEDOR` , `ARMAZENAMENTOS_COMPRAS_PRODUTOS_COD_PRODUTO` , `ARMAZENAMENTOS_ESTOQUES_COD_ESTOQUE` , `ARMAZENAMENTOS_ESTOQUES_SETORES_COD_SETOR`)
    REFERENCES `beowl406_arietama-test`.`ARMAZENAMENTOS` (`COD_ARMAZENAMENTO` , `COMPRAS_COD_ORDEM_COMPRA` , `COMPRAS_FORNECEDORES_COD_FORNECEDOR` , `COMPRAS_PRODUTOS_COD_PRODUTO` , `ESTOQUES_COD_ESTOQUE` , `ESTOQUES_SETORES_COD_SETOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
